# Facebook Configuration
your_page_name: "Todo Sabado a mesma imagem da Hotaru"         # Exact name of your Facebook page (string)
fb_api_version: "v21.0"                                        # Facebook API version (default: v21.0) (string) 

episodes:
  1:
    img_fps: 2                                                # Frame rate used to generate video frames (integer | float)
    album_id: "your_album_id"                                 # Facebook album ID for this episode (integer | string)

  2:
    img_fps: 3.5                                              # Frame rate used to generate video frames (integer | float)
    album_id: 569157099497052                                 # Facebook album ID for this episode (integer | string)

  # add more episodes here


# Posting Configuration
posting:
  fph: 2                                   # Frames per hour (format: integer)
  posting_interval: 2                      # Interval between posts (in minutes) (format: integer)
  posting_subtitles: true                  # Include subtitles in frames
  multi_language_subtitles: true           # Include subtitles in multiple languages

  random_crop:                             # Random crop settings
    enabled: true                          # true or false
    min_x: 200                             # Minimum crop width (format: integer)
    min_y: 600                             # Minimum crop height (format: integer)


random_posting:                            # post frames in random order
  enabled: false                           # true or false
  filters:                                 # Filters to apply to random posting
    enabled: false                         # true or false
    two_panel: false                       # true or false
    mirror_image: false                    # true or false
    negative_filter: false                 # true or false
    generate_palette: false                # true or false
    get_brightness: false                  # true or false
    warp_in: false                         # true or false
    warp_out: false                        # true or false

# Timezone configuration
timezone_offset: "-3"                      # Timezone offset (format: string with sign)

# Message Templates ------------------------------------------------------------------------------------------------

post_message: "Season {season}, Episode {episode}, Frame {current_frame} out of {episode_total_frames}"

random_post_message: |
  "[Random_frame]
  Frame {current_frame} out of {episode_total_frames}, timestamp {frame_timestamp}"

bio_message: |
  "Chopped {img_fps} FPS, Posting {fph} Frames every
  {execution_interval} hours. Total of {total_frames_posted} frames was successfully posted!!!"

# Message Templates --------------------------------------------------------------------------------------------------


# Available variables for message templates:
# - {season}              : Current season number
# - {episode}             : Current episode number
# - {current_frame}       : Current frame number
# - {episode_total_frames}: Total frames in the episode
# - {frame_timestamp}     : Frame timestamp
# - {fph}                 : Frames per interval
# - {page_name}           : Page name
# - {execution_interval}  : Interval between posts
# - {total_frames_posted} : Total frames posted

# - {img_fps}             : Frame rate used to generate video frames
#                           Example ffmpeg command to generate frames:

#                           ffmpeg -i "video.mkv" -vf "fps=2" -fps_mode vfr -q:v 3 frame_%00d.jpg

#                           Where:
#                           - fps=2: sets 2 frames per second 
#                           - fps_mode vfr: variable frame rate mode
#                           - q:v 3: JPEG quality (lower = better)
