name: init banner

on:
  workflow_dispatch:
  schedule:
    # You can change this CRON syntax to customize execute interval
    - cron: "0 */2 * * *"


permissions:
  contents: write
  actions: write

jobs:
  init:
    runs-on: ubuntu-24.04

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FB_TOKEN: ${{ secrets.FB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.13"

      - name: install ImageMagick
        run: |
          sudo apt-get install -y imagemagick

      - name: Is it already running?
        run: |
          WORKFLOW_NAME="${{ github.workflow }}"
          RUN_COUNT=$(gh run list --status=in_progress --json name | jq "[.[] | select(.name == \"$WORKFLOW_NAME\")] | length")
        
          if [ "$RUN_COUNT" -gt 1 ]; then
            echo "The workflow init banner is already running"
            echo "IS_RUNNING=true" >> $GITHUB_ENV
          else
            echo "IS_RUNNING=false" >> $GITHUB_ENV
          fi
     
      - name: Check if episode is available
        run: |
          current_episode=$(grep '^current_episode:' frame_counter.yaml | awk '{print $2}')

          if [ -z "$current_episode" ]; then
            echo "Error: current_episode not found or empty in frame_counter.yaml"
            exit 1
          fi

          if [ "$current_episode" -lt 10 ]; then
            current_episode="0$current_episode"
          fi

          if [ ! -d "episodes/frames/$current_episode" ]; then
            echo "No more episodes"
            exit 1
          fi
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      # checa se o processo está rodando, se true, não roda o main.py
      - name: Main
        run: |
          if [[ "$IS_RUNNING" == "false" ]]; then 
            python main.py
          fi
          

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update"
          file_pattern: "frame_counter.yaml sys/Error.log"
