name: init banner

on:
  workflow_dispatch:
  schedule:
    # You can change this CRON syntax to customize execute interval
    - cron: "0 */2 * * *"


permissions:
  contents: write
  actions: write

jobs:
  init:
    runs-on: ubuntu-24.04

    env:

      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}       # GitHub Token for CLI
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # GitHub Token for Actions
      FB_TOKEN: ${{ secrets.FB_TOKEN }}           # Facebook Token

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.13"
      
      # checa se o workflow já está rodando, se sim, não roda o main.py
      - name: Is it already running?
        run: |
          WORKFLOW_NAME="${{ github.workflow }}"
          RUN_COUNT=$(gh run list --status=in_progress --json name |
            jq "[.[] | select(.name == \"$WORKFLOW_NAME\")] | length")
        
          if [ "$RUN_COUNT" -gt 1 ]; then
            echo "The workflow init banner is already running"
            echo "IS_RUNNING=true" >> $GITHUB_ENV
          else
            echo "IS_RUNNING=false" >> $GITHUB_ENV
          fi
      
      # checa se o episódio está disponível, se não, sai do workflow com erro
      - name: Check if episode is available
        run: |
          current_episode=$(grep '^current_episode:' frame_counter.yaml | awk '{print $2}')

          if [ -z "$current_episode" ]; then
            echo "Error: current_episode not found or empty in frame_counter.yaml"
            exit 1
          fi

          if [ "$current_episode" -lt 10 ]; then
            current_episode="0$current_episode"
          fi

          if [ ! -d "episodes/frames/$current_episode" ]; then
            echo "No more episodes"
            exit 1
          fi

      # cache de dependencias
      - name: Cache dependencies
        uses: actions/cache@v4.2.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('sys/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      # instala dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      # So roda o main.py se o workflow não estiver rodando
      - name: Main
        run: |
          if [[ "$IS_RUNNING" != "true" ]]; then 
            python main.py
          fi
          

      # atualiza variaveis que serão usadas no próximo workflow
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update"
          file_pattern: "frame_counter.yaml sys/Error.log"
