name: 01_init

on:
  workflow_dispatch:
  schedule:
    # You can change this CRON syntax to customize execute interval
    - cron: "0 */2 * * *"

permissions:
  contents: write
  actions: write

jobs:
  init:
    runs-on: ubuntu-22.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FB_TOKEN: ${{ secrets.FB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: check if episode is available
        run: |
          if [ -f "frame_counter.txt" ]; then
            current_episode=$(grep "^current_episode:" "frame_counter.txt" | cut -d ':' -f2 | tr -d ' ')

            if [ -z "$current_episode" ]; then
              echo "current_episode not found in frame_counter.txt."
              exit 1
            fi

            episode_count=$(find "episodes/frames" -mindepth 1 -maxdepth 1 -type d | wc -l)

            if [ "$current_episode" -gt "$episode_count" ]; then
              echo "No more episodes available."
              exit 1
              fi
          fi
      
      # if you need to install imageMagick
      # - name: install imageMagick
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y imagemagick
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Main
        run: |
          python main.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update"
          file_pattern: "frame_counter.txt sys/Error.log"
