name: check variables

on: [push]

jobs:
    check-variables:
        runs-on: ubuntu-24.04

        env:
          FB_TOKEN: ${{ secrets.FB_TOKEN }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Set up Python
              uses: actions/setup-python@v5.4.0
              with:
                python-version: "3.13"

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip 
                pip install -r requirements.txt 
        
            - name: Run FB Token Check
              run: |
                python -m checkers.variable_checks