name: "first_process"

on:
  workflow_dispatch:
  schedule:
     # You can change this CRON syntax to customize execute interval
     - cron: "0 */2 * * *"
  

permissions:
  contents: write
  actions: write

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Get workflow ID for second process"
        id: get_workflow_id
        run: |
          workflow_id=$(curl -s -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
          https://api.github.com/repos/${{github.repository}}/actions/workflows | jq -r '.workflows[] | select(.name == "second_process") | .id')
          
          echo "workflow_id=$workflow_id" >> $GITHUB_ENV

      - name: "Check if second process is running"
        run: |
          status=$(curl -s -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
          https://api.github.com/repos/${{github.repository}}/actions/workflows/$workflow_id/runs | jq -r '.workflow_runs[0].status')

          if [[ "$status" == "in_progress" ]]; then
            echo "second process is running"
            exit 1
          else
            runSecondProcess=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
            -X POST \
            https://api.github.com/repos/${{github.repository}}/actions/workflows/$workflow_id/dispatches \
            -d "{\"ref\":\"${{ github.ref_name }}\"}")
            echo "$runSecondProcess"
          fi

          
          
        
      





