# Don't change this `name` below, the script might broke at some point
name: Init

on:
  workflow_dispatch:
  schedule:
     # You can change this CRON syntax to customize execute interval
     - cron: "0 */2 * * *"

  

permissions:
  contents: write
  actions: write

jobs:
  init:
    runs-on: ubuntu-22.04

    env:
      FB_TOKEN: ${{ secrets.FB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Progress"
          skip_dirty_check: false
          file_pattern: |
            configs.yaml
            frame_couter.txt
            sys/*.log



