# Don't change this `name` below, the script might broke at some point
name: Init

on:
  workflow_dispatch:
  schedule:
     # You can change this CRON syntax to customize execute interval
     - cron: "0 */2 * * *"

  

permissions:
  contents: write
  actions: write

jobs:
  init:
    runs-on: ubuntu-22.04

    env:
      FB_TOKEN: ${{ secrets.FB_TOKEN }}

    steps:
      - name: Cache pip and other dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.local/lib/python3.13/site-packages
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.13
          architecture: x64
      
      - name: Upgrade pip to latest stable
        run: |
          python -m pip install --upgrade pip || { echo 'Pip upgrade failed'; exit 1; }
      
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt || { echo 'Dependency installation failed'; exit 1; }

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Progress"
          skip_dirty_check: false
          file_pattern: |
            configs.yaml
            frame_couter.txt
            sys/*.log



