name: second process


on:
    workflow_dispatch:
    workflow_run:
        workflows: ["first_process"]
        types:
            - completed


permissions:
    contents: write
  
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    second_process:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: run_main.py
              run: |
                  python main.py

    
            - name: auto-commit
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "auto-commit"
                  file_pattern: text.txt


