name: second_process

on:
    workflow_dispatch:

permissions:
    contents: write
    actions: write


jobs:
    checks:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: "run main"
              run: |
                python main.py
