name: "Checking permissions"

on:
    workflow_dispatch:
    schedule:
        - cron: "*/5 * * * *"

permissions:
    contents: write

jobs:
    
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: run script
              run: |
                  python main.py
                  
            - name: "commit changes"
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: "auto commit"
                file_pattern: "text.txt"
            
            
                